### ISSUE TITLE
Version 0.2.86 breaks with jest-environment-jsdom

### ISSUE THREAD

**Issue by anomiex** [dmonad/lib0#79]
**Describe the bug**
When running tests using jest and jest-environment-jsdom, version 0.2.86 of this package causes a failure:
```
 FAIL  ./test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /tmp/test/node_modules/lib0/webcrypto.js:3
    export const subtle = crypto.subtle
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      3 |  */
      4 |
    > 5 | const random = require( 'lib0/random' );
        |                ^
      6 |
      7 | test( 'it works', () => {
      8 |     const element = document.createElement('div');

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (node_modules/lib0/dist/random.cjs:7:17)
      at Object.require (test.js:5:16)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.325 s
```
It worked with 0.2.85.

**To Reproduce**
1. Create an empty directory for the test.
2. Run `npm add jest jest-environment-jsdom lib0`
3. Create the following file named `test.js`:
   ```js
   /**
    * @jest-environment jsdom
    */
   
   const random = require( 'lib0/random' );
   
   test( 'it works', () => {
       const element = document.createElement('div');
       expect( element ).not.toBeNull();
   } );
   ```
5. Run `npm exec jest test.js`
6. See error

**Expected behavior**
Test passes, along the lines of
```
 PASS  ./test.js
  ✓ it works (2 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.379 s
```

**Environment Information**
 - Node.js
 - Which version are you using? v18.17.1

**Additional context**
The cause is https://github.com/dmonad/lib0/commit/4b4faaad72c5fc28efe349cccb6bf9c202234cee. With jest-environment-jsdom the conditions available are "browser", "require" (not "import"), and "default", but that commit assumes "browser" always comes with "import".

A detailed analysis of a similar problem in another package, along with potential workarounds, may be found at https://github.com/microsoft/accessibility-insights-web/pull/5421#issuecomment-1109168149.

**Comment by dmonad** [comment]
This should be fixed in the next release. Please reopen the ticket if the issue persists.

**Comment by anomiex** [comment]
It works, thanks!
